name: call reuse workflow
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo 'staring ....'

  refer:
    uses: ./.github/workflows/reuse.yaml
    
