name: conditional workflow execution
on: workflow_dispatch
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "First Step!"

      - name: second step
        id: step2
        run: echofequifg "Second Step!"

      - name: third step
        if: steps.step2.outcome == 'failure'
        run: echo "Third Step!"

      - name: fourth step
        run: echo "Fourth Step!"

      
