name: Matrix Strategy
on: workflow_dispatch
jobs:
  first:
    continue-on-error: true
    strategy:
      matrix:
        node-versions: [12, 14, 16]
        os-type: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os-type }}
    steps:
      - name: checkout 
        uses: actions/checkout@v4

      - name: setup node.js envionment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-versions }}

      - name: install dependencies
        run: npm ci

      - name: run test
        run: npm run test
