name: test and build 
on: [ workflow_dispatch, push ]
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout on the code
        uses: actions/checkout@v4
        
      - name: install all dependenicies
        run: npm ci

      - name: run lint test
        run: |
          npm run lint

      - name: run test
        run: npm run test

      - name: build
        run: npm run build

      

      
        
